name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package

      - name: Run Tests
        run: mvn test

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-jar
          path: target/*.jar

      - name: Deploy JAR to WSL Ubuntu via SCP
        run: |
          sudo apt-get install sshpass -y
          sshpass -p "$DEPLOY_PASS" scp -o StrictHostKeyChecking=no target/*.jar $DEPLOY_USER@$DEPLOY_HOST:/home/$DEPLOY_USER/deploy/
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}

      - name: Run JAR on WSL Ubuntu via SSH
        run: |
          sshpass -p "$DEPLOY_PASS" ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "java -jar /home/$DEPLOY_USER/deploy/*.jar || echo 'App ran and exited (simulated deployment)'"
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}
